/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.demo.webservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Studio service. Represents a row in the &quot;Studio_Studio&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.demo.webservice.model.impl.StudioModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.demo.webservice.model.impl.StudioImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Studio
 * @generated
 */
@ProviderType
public interface StudioModel extends BaseModel<Studio> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a studio model instance should use the {@link Studio} interface instead.
	 */

	/**
	 * Returns the primary key of this studio.
	 *
	 * @return the primary key of this studio
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this studio.
	 *
	 * @param primaryKey the primary key of this studio
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this studio.
	 *
	 * @return the uuid of this studio
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this studio.
	 *
	 * @param uuid the uuid of this studio
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the studio ID of this studio.
	 *
	 * @return the studio ID of this studio
	 */
	public long getStudioId();

	/**
	 * Sets the studio ID of this studio.
	 *
	 * @param studioId the studio ID of this studio
	 */
	public void setStudioId(long studioId);

	/**
	 * Returns the camera name of this studio.
	 *
	 * @return the camera name of this studio
	 */
	@AutoEscape
	public String getCameraName();

	/**
	 * Sets the camera name of this studio.
	 *
	 * @param cameraName the camera name of this studio
	 */
	public void setCameraName(String cameraName);

	/**
	 * Returns the camera model of this studio.
	 *
	 * @return the camera model of this studio
	 */
	@AutoEscape
	public String getCameraModel();

	/**
	 * Sets the camera model of this studio.
	 *
	 * @param cameraModel the camera model of this studio
	 */
	public void setCameraModel(String cameraModel);

	/**
	 * Returns the camera price of this studio.
	 *
	 * @return the camera price of this studio
	 */
	public long getCameraPrice();

	/**
	 * Sets the camera price of this studio.
	 *
	 * @param cameraPrice the camera price of this studio
	 */
	public void setCameraPrice(long cameraPrice);

	@Override
	public Studio cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}