/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.demo.webservice.model.impl;

import com.demo.webservice.model.Studio;
import com.demo.webservice.service.StudioLocalServiceUtil;

/**
 * The extended model base implementation for the Studio service. Represents a row in the &quot;Studio_Studio&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link StudioImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StudioImpl
 * @see Studio
 * @generated
 */
public abstract class StudioBaseImpl extends StudioModelImpl implements Studio {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a studio model instance should use the <code>Studio</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			StudioLocalServiceUtil.addStudio(this);
		}
		else {
			StudioLocalServiceUtil.updateStudio(this);
		}
	}

}