apiDir: "../Sample-Headless-api/src/main/java"
apiPackagePath: "com.demo.rest"
application:
    baseURI: "/Sample-Headless"
    className: "SampleHeadlessApplication"
    name: "SampleHeadless"
author: "Suchismita"