/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.demo.builder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Student service. Represents a row in the &quot;BUILD_Student&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.demo.builder.model.impl.StudentModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.demo.builder.model.impl.StudentImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Student
 * @generated
 */
@ProviderType
public interface StudentModel extends BaseModel<Student> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a student model instance should use the {@link Student} interface instead.
	 */

	/**
	 * Returns the primary key of this student.
	 *
	 * @return the primary key of this student
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this student.
	 *
	 * @param primaryKey the primary key of this student
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this student.
	 *
	 * @return the uuid of this student
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this student.
	 *
	 * @param uuid the uuid of this student
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the stu ID of this student.
	 *
	 * @return the stu ID of this student
	 */
	public long getStuId();

	/**
	 * Sets the stu ID of this student.
	 *
	 * @param stuId the stu ID of this student
	 */
	public void setStuId(long stuId);

	/**
	 * Returns the stu name of this student.
	 *
	 * @return the stu name of this student
	 */
	@AutoEscape
	public String getStuName();

	/**
	 * Sets the stu name of this student.
	 *
	 * @param stuName the stu name of this student
	 */
	public void setStuName(String stuName);

	/**
	 * Returns the stu address of this student.
	 *
	 * @return the stu address of this student
	 */
	@AutoEscape
	public String getStuAddress();

	/**
	 * Sets the stu address of this student.
	 *
	 * @param stuAddress the stu address of this student
	 */
	public void setStuAddress(String stuAddress);

	/**
	 * Returns the stu age of this student.
	 *
	 * @return the stu age of this student
	 */
	public int getStuAge();

	/**
	 * Sets the stu age of this student.
	 *
	 * @param stuAge the stu age of this student
	 */
	public void setStuAge(int stuAge);

	/**
	 * Returns the stu join date of this student.
	 *
	 * @return the stu join date of this student
	 */
	public Date getStuJoinDate();

	/**
	 * Sets the stu join date of this student.
	 *
	 * @param stuJoinDate the stu join date of this student
	 */
	public void setStuJoinDate(Date stuJoinDate);

	/**
	 * Returns the stu phone no of this student.
	 *
	 * @return the stu phone no of this student
	 */
	public long getStuPhoneNo();

	/**
	 * Sets the stu phone no of this student.
	 *
	 * @param stuPhoneNo the stu phone no of this student
	 */
	public void setStuPhoneNo(long stuPhoneNo);

	@Override
	public Student cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}